from flask import Flask, request
import json

# --------------------------------------------------------------
# 1) Download Ngrok
# 2) In the prompt (from the directory containing the ngrok.exe file):
#    ngrok config add-authtoken 2dE7....
# 3) In the prompt - to create the tunnel local host (port 5000) to internet
#    ngrok http 5000
# 4) Copy the link generated by Ngrok under "Forwarding" + '/webhookcallback' from where the webhook will be sent
# --------------------------------------------------------------


app = Flask(__name__)


# --------------------------------------------------------------
# Define endpoint
# --------------------------------------------------------------
@app.route("/webhookcallback", methods=["GET", "POST"])
def hook():
    print(request.data)
    jdata = json.loads(request.data)
    jdata_formatted = json.dumps(jdata, indent=2)
    print(jdata_formatted)
    return "Hello World"


if __name__ == "__main__":
    app.run()
